// Auto-generated by MSBuild. Do not edit.
[assembly: System.Reflection.AssemblyVersion("2026.8.23.0")]
[assembly: System.Reflection.AssemblyFileVersion("2026.8.23.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("2026.8.23")]
